"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BrainCircuit, Building2, CalendarRange, Check, ChevronRight, CircleDollarSign, HeartHandshake, MapPinned, Megaphone, RefreshCw, Route, Send, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { ProductShell } from "../components/ProductShell";
import { Reveal } from "../components/Reveal";
import { api } from "../utils/api";
import type { DashboardSummary } from "../types";

const months = ["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค."];
const opportunities = [62, 58, 54, 48, 74, 82, 88, 86, 79, 71, 64, 59];

export default function MissionControlPage() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [month, setMonth] = useState(5);
  const [mission, setMission] = useState<"ready" | "sent">("ready");
  const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.getDashboardSummary().then(setSummary).finally(() => setLoading(false)); };
  useEffect(load, []);
  const evidence = useMemo(() => Object.values(summary?.entities || {}).reduce((sum, value) => sum + value, 0), [summary]);
  const opportunity = opportunities[month];

  return <ProductShell title="Nan Mission Control" description="Province View · decide, activate and learn" action={<button className="secondary-button hidden sm:inline-flex" onClick={load}><RefreshCw size={15} /> อัปเดตสัญญาณ</button>}>
    <Reveal><section className="mission-hero overflow-hidden rounded-[32px] p-6 text-white sm:p-9 lg:p-11"><div className="grid gap-10 xl:grid-cols-[1.25fr_.75fr]"><div><div className="flex flex-wrap items-center gap-3"><span className="chip border-white/15 bg-white/10 text-white"><Sparkles size={13}/> AI Decision Center</span><span className="text-xs opacity-55">{loading ? "กำลังเชื่อมข้อมูล" : `${evidence} knowledge signals`}</span></div><p className="mt-9 text-xs font-bold uppercase tracking-[.18em] opacity-55">Today&apos;s Mission</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl lg:text-6xl">Coffee &amp; Craft Week</h2><p className="mt-3 text-xs font-bold uppercase tracking-[.16em] text-[#9fd0bc]">Recommended campaign</p><div className="mt-7 grid max-w-2xl gap-2 sm:grid-cols-2">{["3 communities need support","Coffee harvest starts tomorrow","Festival begins in 2 days","Weather is ideal"].map((signal)=><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.06] px-4 py-3 text-xs font-bold" key={signal}><span className="status-dot bg-[#9fd0bc]"/>{signal}</div>)}</div><div className="mt-8 flex flex-wrap gap-3"><button className="primary-button bg-white text-[#10201b]" onClick={()=>setMission("sent")} disabled={mission==="sent"}>{mission==="sent"?<><Check size={16}/> ส่งภารกิจแล้ว</>:<><Send size={16}/> Activate Campaign</>}</button><button className="secondary-button border-white/15 bg-white/5 text-white"><BrainCircuit size={16}/> ดูเหตุผลของ AI</button></div></div><aside className="grid grid-cols-3 gap-2 self-end xl:grid-cols-1">{[{label:"Communities supported",value:"3",icon:Users},{label:"Campaign readiness",value:"2 days",icon:Building2},{label:"Opportunity window",value:"Now",icon:CircleDollarSign}].map(({label,value,icon:Icon})=><div className="rounded-2xl border border-white/10 bg-white/[.07] p-4 sm:p-5" key={label}><Icon size={17} className="opacity-60"/><strong className="mt-5 block text-2xl sm:text-3xl">{value}</strong><span className="mt-1 block text-[10px] leading-4 opacity-55">{label}</span></div>)}</aside></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 border-t border-white/10 pt-5 text-xs opacity-60"><span>AI detected 4 converging signals</span><span>Evidence: {loading?"—":evidence} nodes</span><span>Requires community confirmation</span><span>Weather and timing must be revalidated before launch</span></div></section></Reveal>

    <div className="mt-6 grid gap-6 xl:grid-cols-[.78fr_1.22fr]"><Reveal><section className="decision-card h-full"><div className="flex items-start justify-between"><div><p className="eyebrow">Community Health</p><h2 className="section-title mt-2">ความพร้อมของระบบชุมชน</h2></div><HeartHandshake style={{color:"var(--mint)"}}/></div><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-3xl p-5" style={{background:"var(--mint-light)"}}><strong className="metric-value">72%</strong><p className="mt-3 text-xs font-bold">Healthy</p><p className="mt-1 text-[11px]" style={{color:"var(--tertiary)"}}>พร้อมรับโอกาสอย่างสมดุล</p></div><div className="surface rounded-3xl p-5"><strong className="metric-value">28%</strong><p className="mt-3 text-xs font-bold">Need Support</p><p className="mt-1 text-[11px]" style={{color:"var(--tertiary)"}}>ต้องการ capacity หรือการประสานงาน</p></div></div><button className="secondary-button mt-5 w-full">เปิด Support Queue <ArrowRight size={14}/></button></section></Reveal><Reveal delay={.05}><section className="decision-card"><div className="flex items-start justify-between"><div><p className="eyebrow">12-Month Opportunity Engine</p><h2 className="section-title mt-2">เลือกเดือนเพื่อจำลองโอกาส</h2></div><CalendarRange style={{color:"var(--mint)"}}/></div><div className="mt-8 grid grid-cols-6 gap-2 xl:grid-cols-12">{months.map((item,index)=><button aria-pressed={month===index} onClick={()=>setMonth(index)} className={`month-cell ${month===index?"month-cell-active":""}`} key={item}><span>{item}</span><i style={{height:`${Math.max(12,opportunities[index]*.55)}px`}}/></button>)}</div><div className="mt-6 flex flex-col gap-4 rounded-2xl p-4 sm:flex-row sm:items-center" style={{background:"var(--mint-light)"}}><div><p className="text-xs font-bold">{months[month]} · Opportunity {opportunity}/100</p><p className="mt-1 text-xs" style={{color:"var(--muted)"}}>{opportunity>=80?"เหมาะกับการเปิดประสบการณ์ใหม่ในพื้นที่รอง":"รักษาสมดุลและเพิ่ม readiness ก่อนขยาย demand"}</p></div><button className="secondary-button ml-auto shrink-0">สร้าง Scenario</button></div></section></Reveal></div>

    <Reveal><section className="mt-6 decision-card"><div className="flex items-start justify-between"><div><p className="eyebrow">Economic Flow</p><h2 className="section-title mt-2">มูลค่าไหลเข้าสู่เศรษฐกิจพื้นที่อย่างไร</h2></div><CircleDollarSign style={{color:"var(--gold)"}}/></div><div className="economic-flow mt-9"><div className="flow-node"><Megaphone size={19}/><span>Mission</span></div><ChevronRight/><div className="flow-node"><Route size={19}/><span>Experience</span></div><ChevronRight/><div className="flow-node"><Building2 size={19}/><span>Local Business</span></div><ChevronRight/><div className="flow-node"><Users size={19}/><span>Families</span></div><ChevronRight/><div className="flow-node"><HeartHandshake size={19}/><span>Community Fund</span></div><span className="flow-pulse" aria-hidden="true"/></div><p className="mt-7 text-xs" style={{color:"var(--tertiary)"}}>ภาพจำลองการไหลของมูลค่า ต้องยืนยันด้วยข้อมูล transaction และ community reporting ก่อนใช้เป็นผลกระทบจริง</p></section></Reveal>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Reveal><section className="decision-card"><div className="flex items-start justify-between"><div><p className="eyebrow">Community Impact Heatmap</p><h2 className="section-title mt-2">พื้นที่ที่ได้รับคุณค่าและพื้นที่ที่ต้องดูแล</h2></div><MapPinned style={{color:"var(--clay)"}}/></div><div className="impact-map mt-7" role="img" aria-label="Conceptual community impact heatmap across Nan"><span className="impact-spot impact-good" style={{left:"24%",top:"24%"}}>ปัว<small>Growing</small></span><span className="impact-spot impact-watch" style={{left:"54%",top:"43%"}}>เมืองน่าน<small>Watch load</small></span><span className="impact-spot impact-opportunity" style={{left:"35%",top:"68%"}}>เวียงสา<small>Opportunity</small></span><span className="impact-spot impact-good" style={{left:"72%",top:"72%"}}>นาน้อย<small>Healthy</small></span></div><div className="mt-5 flex flex-wrap gap-4 text-xs" style={{color:"var(--tertiary)"}}><span>● Healthy impact</span><span>● Opportunity</span><span>● Monitor community load</span></div></section></Reveal><Reveal delay={.05}><section className="decision-card h-full"><Target size={22} style={{color:"var(--mint)"}}/><p className="eyebrow mt-5">Hidden Opportunities</p><h2 className="section-title mt-2">AI พบพื้นที่ที่ยังไม่ถูกมองเห็น</h2><div className="mt-7 space-y-3">{[{place:"บ่อเกลือ · กลางสัปดาห์",reason:"ความสนใจสูง แต่ demand ยังต่ำ"},{place:"นาน้อย · งานฝีมือ",reason:"มีเรื่องราวและผู้ประกอบการพร้อม"},{place:"เวียงสา · อาหารท้องถิ่น",reason:"ตอบ Community Need นอกฤดูกาล"}].map((item,index)=><button className="surface flex w-full items-center gap-4 rounded-2xl p-4 text-left" key={item.place}><span className="grid size-9 shrink-0 place-items-center rounded-xl text-xs font-bold" style={{background:"var(--mint-light)",color:"var(--forest)"}}>0{index+1}</span><span><strong className="block text-xs">{item.place}</strong><small className="mt-1 block" style={{color:"var(--tertiary)"}}>{item.reason}</small></span><ArrowRight className="ml-auto" size={14}/></button>)}</div></section></Reveal></div>

    <Reveal><section className="mt-6 rounded-[32px] p-6 sm:p-9" style={{background:"var(--forest)",color:"var(--canvas)"}}><div className="grid gap-8 lg:grid-cols-[.55fr_1.45fr]"><div><TrendingUp size={24}/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] opacity-55">30-Day AI Forecast</p><h2 className="mt-3 text-3xl font-semibold">สิ่งที่จังหวัดควรทำต่อ</h2></div><div className="grid gap-3 md:grid-cols-3">{[{when:"ภายใน 7 วัน",action:"ยืนยัน capacity กับ 3 ชุมชนในเวียงสา"},{when:"ภายใน 14 วัน",action:"แจ้ง 18 ผู้ประกอบการให้เตรียมข้อเสนอร่วม"},{when:"ภายใน 30 วัน",action:"ปรับเส้นทางแนะนำเพื่อกระจาย demand จากเมืองน่าน"}].map((item,index)=><article className="rounded-2xl border border-white/10 bg-white/5 p-5" key={item.when}><span className="text-xs opacity-45">0{index+1}</span><p className="mt-7 text-xs font-bold opacity-65">{item.when}</p><p className="mt-3 text-sm font-bold leading-6">{item.action}</p><button className="mt-6 flex items-center gap-2 text-xs font-bold">มอบหมายงาน <ArrowRight size={13}/></button></article>)}</div></div></section></Reveal>
  </ProductShell>;
}
