"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, BookOpenCheck, BrainCircuit, CalendarRange, CheckCircle2, CircleDollarSign, CircleGauge, Database, RefreshCw, Route, Target, Users } from "lucide-react";
import { ProductShell } from "../components/ProductShell";
import { Reveal } from "../components/Reveal";
import { api } from "../utils/api";
import type { DashboardSummary } from "../types";

export default function DashboardPage() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.getDashboardSummary().then(setSummary).finally(() => setLoading(false)); };
  useEffect(load, []);
  const total = Object.values(summary?.entities || {}).reduce((sum,value) => sum+value,0);
  const labels = Object.entries(summary?.entities || {}).sort((a,b) => b[1]-a[1]);

  return <ProductShell title="Decision Dashboard" description="Province View · decisions, distribution and 12-month opportunity" action={<button className="secondary-button hidden sm:inline-flex" onClick={load}><RefreshCw size={15} /> อัปเดต</button>}>
    <Reveal><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Province View</p><h2 className="page-title mt-3">จังหวัดควรตัดสินใจอะไรต่อ</h2><p className="body-copy mt-4">เชื่อมความต้องการนักท่องเที่ยว ความต้องการชุมชน และเป้าหมายการกระจายมูลค่าเป็นระบบเดียว</p></div><span className="chip chip-active"><span className="status-dot bg-white" /> Supabase connected</span></div></Reveal>

    <Reveal><section className="mt-9 grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr] lg:items-stretch"><article className="decision-card"><Route size={20} style={{color:"var(--river)"}}/><p className="eyebrow mt-5">Tourist View</p><h3 className="mt-2 text-lg font-bold">ความตั้งใจและประสบการณ์</h3><p className="body-copy mt-2 text-xs">ส่งสัญญาณความสนใจ ช่วงเวลา และจังหวะการเดินทาง</p></article><ArrowRight className="m-auto hidden lg:block" style={{color:"var(--tertiary)"}}/><article className="decision-card"><Target size={20} style={{color:"var(--mint)"}}/><p className="eyebrow mt-5">Community View</p><h3 className="mt-2 text-lg font-bold">Need, Capacity, Consent</h3><p className="body-copy mt-2 text-xs">กำหนดเป้าหมาย เงื่อนไข ความพร้อม และสิทธิ์ในการหยุด</p></article><ArrowRight className="m-auto hidden lg:block" style={{color:"var(--tertiary)"}}/><article className="decision-card"><CircleGauge size={20} style={{color:"var(--gold)"}}/><p className="eyebrow mt-5">Province View</p><h3 className="mt-2 text-lg font-bold">กระจายคนและมูลค่า</h3><p className="body-copy mt-2 text-xs">เลือก intervention ที่สร้างโอกาสตลอด 12 เดือน</p></article></section></Reveal>

    <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:"Knowledge nodes",value:loading?"—":String(total),icon:Database},{label:"Active categories",value:loading?"—":String(labels.length),icon:CircleGauge},{label:"Communities",value:loading?"—":String(summary?.entities.Community||0),icon:Users},{label:"Published stories",value:loading?"—":String(summary?.posts.approved||0),icon:BookOpenCheck}].map(({label,value,icon:Icon},index) => <Reveal delay={index*.04} key={label}><article className="soft-card"><Icon size={19} style={{ color:"var(--mint)" }} /><strong className="metric-value mt-7 block">{value}</strong><span className="mt-2 block text-xs font-bold" style={{ color:"var(--muted)" }}>{label}</span></article></Reveal>)}</div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <Reveal><section className="decision-card"><div className="flex items-start justify-between"><div><p className="eyebrow">Priority queue</p><h2 className="section-title mt-2">Decisions requiring attention</h2></div><span className="chip">3 items</span></div><div className="mt-7 divide-y" style={{ borderColor:"var(--line)" }}>{[
        {icon:AlertTriangle,title:"Environmental load approaching threshold",meta:"Northern route · review within 24h",tone:"var(--warning)",action:"Review impact"},
        {icon:Users,title:"Community readiness requires confirmation",meta:"2 communities · December window",tone:"var(--mint)",action:"Request confirmation"},
        {icon:CheckCircle2,title:"Knowledge validation completed",meta:"6 records ready for publication",tone:"var(--river)",action:"Review evidence"},
      ].map(({icon:Icon,title,meta,tone,action}) => <article className="flex flex-col gap-4 py-5 first:pt-0 sm:flex-row sm:items-center" key={title}><span className="grid size-11 shrink-0 place-items-center rounded-2xl" style={{ color:tone, background:`color-mix(in srgb, ${tone} 15%, transparent)` }}><Icon size={19} /></span><div className="min-w-0"><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs" style={{ color:"var(--tertiary)" }}>{meta}</p></div><button className="secondary-button ml-auto min-h-10 shrink-0 px-4">{action} <ArrowRight size={14} /></button></article>)}</div></section></Reveal>

      <Reveal delay={.08}><section className="decision-card h-full"><p className="eyebrow">Knowledge composition</p><h2 className="section-title mt-2">Connected memory</h2><div className="mt-7 space-y-5">{labels.slice(0,7).map(([label,count]) => { const pct=total?Math.round(count/total*100):0; return <div key={label}><div className="flex justify-between text-xs font-bold"><span>{label}</span><span style={{ color:"var(--tertiary)" }}>{count} · {pct}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full" style={{ background:"var(--line)" }}><div className="h-full rounded-full" style={{ width:`${pct}%`, background:"var(--mint)" }} /></div></div>})}</div></section></Reveal>
    </div>

    <Reveal><section className="mt-6 grid gap-4 md:grid-cols-3">{[{title:"Demand redistribution",text:"Low-season cultural interest is rising",value:"+18%"},{title:"Local value retention",text:"Across active experience chains",value:"78%"},{title:"Decision evidence",text:"Recommendations with citations",value:"100%"}].map(({title,text,value}) => <article className="soft-card" key={title}><span className="eyebrow">Signal</span><strong className="metric-value mt-6 block">{value}</strong><h3 className="mt-5 text-sm font-bold">{title}</h3><p className="mt-2 text-xs" style={{ color:"var(--tertiary)" }}>{text}</p></article>)}</section></Reveal>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Reveal><section className="decision-card"><div className="flex items-start justify-between"><div><p className="eyebrow">12-Month Opportunity Engine</p><h2 className="section-title mt-2">Opportunity portfolio</h2></div><CalendarRange style={{color:"var(--mint)"}}/></div><div className="mt-7 grid grid-cols-3 gap-2 sm:grid-cols-6">{["ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค."].map((month,index)=><div className="rounded-2xl border p-3 text-center" style={{borderColor:"var(--line)",background:index>=4&&index<=9?"var(--mint-light)":"var(--surface)"}} key={month}><strong className="text-xs">{month}</strong><span className="mt-2 block text-[10px]" style={{color:"var(--tertiary)"}}>{index>=4&&index<=9?"สร้างโอกาส":"รักษาสมดุล"}</span></div>)}</div><p className="body-copy mt-5 text-xs">สถานะนี้เป็นกรอบการตัดสินใจ ระบบจริงต้องคำนวณจาก demand, community readiness, capacity และ impact observations รายเดือน</p></section></Reveal><Reveal delay={.06}><section className="decision-card h-full"><CircleDollarSign size={22} style={{color:"var(--gold)"}}/><p className="eyebrow mt-5">Economic Flow</p><h2 className="section-title mt-2">มูลค่าไหลไปที่ใคร</h2><div className="mt-6 space-y-3">{["เจ้าของประสบการณ์ชุมชน","ผู้ประกอบการท้องถิ่น","ผู้ผลิตและช่างฝีมือ","กองทุนชุมชน"].map((item,index)=><div className="flex items-center gap-3" key={item}><span className="grid size-8 place-items-center rounded-full text-xs font-bold" style={{background:"var(--mint-light)",color:"var(--forest)"}}>{index+1}</span><span className="text-xs font-bold">{item}</span></div>)}</div></section></Reveal></div>

    <Reveal><section className="mt-6 rounded-[28px] p-6 sm:p-8" style={{background:"var(--forest)",color:"var(--canvas)"}}><div className="grid gap-7 lg:grid-cols-[.45fr_1fr]"><div><BrainCircuit size={24}/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] opacity-60">AI Decision Reasoning</p><h2 className="mt-3 text-2xl font-bold">เหตุผลก่อนคำแนะนำ</h2></div><div className="grid gap-3 sm:grid-cols-3">{[{title:"Observe",text:"อ่าน demand, need และ capacity"},{title:"Reason",text:"ตัดทางเลือกที่ขัดข้อจำกัด"},{title:"Decide",text:"จัดลำดับตาม impact และหลักฐาน"}].map((item,index)=><article className="rounded-2xl border border-white/10 bg-white/5 p-4" key={item.title}><span className="text-xs opacity-50">0{index+1}</span><h3 className="mt-7 text-sm font-bold">{item.title}</h3><p className="mt-2 text-xs leading-5 opacity-65">{item.text}</p></article>)}</div></div></section></Reveal>
  </ProductShell>;
}
